<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Common\Shared.props" />
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Description>Adds TemporaryTransform on TestHelper.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.SqlServer.Transform\CK.SqlServer.Transform.csproj" />
    <PackageReference Include="CK.Testing.Monitoring" Version="3.0.0-r06-02-0008-develop" />
  </ItemGroup>
</Project>