<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Adds TemporaryTransform on TestHelper.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.SqlServer.Transform\CK.SqlServer.Transform.csproj" />
    <PackageReference Include="CK.Testing.Monitoring" Version="13.0.0" />
  </ItemGroup>
</Project>