<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Common\Shared.props" />
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <IsTestProject>False</IsTestProject>
    <IsPackable>False</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.SqlServer.Parser\CK.SqlServer.Parser.csproj" />
    <ProjectReference Include="..\..\CK.Testing.SqlTransform\CK.Testing.SqlTransform.csproj" />
    <PackageReference Include="NUnit" Version="3.12.0" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>