<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Common\Shared.props" />
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <IsPackable>False</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.SqlServer.Transform\CK.SqlServer.Transform.csproj" />
    <ProjectReference Include="..\CK.SqlServer.UtilTests\CK.SqlServer.UtilTests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.1.0" />
  </ItemGroup>
</Project>