<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Common\Shared.props" />
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
    <Description>T-Sql parser implementation.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.ActivityMonitor.SimpleSender" Version="12.1.1--0010-develop" />
    <PackageReference Include="CK.SqlServer.Parser.Model" Version="9.1.1--0004-develop" />
    <PackageReference Include="System.Collections.Immutable" Version="1.5.0" />
  </ItemGroup>
</Project>